[package]
name = "simreader"
version = "0.1.0"
edition = "2024"
description = "A Simple Reader for data files and txt files in Rust."
license = "MIT"
authors = ["Sidney Zhang <zly@lyzhang.me>"]
repository = "https://github.com/SidneyLYZhang/simreader"


[dependencies]
calamine = { version = "0.34.0", features = ["chrono"] }
clap = { version = "4.6.1", features = ["derive", "color"] }
polars = { version = "0.53.0", features = ["csv","json","polars-parquet","lazy","ipc"] }
